#!/bin/bash

rm -rf docs

mkdir -p ./docs

echo "theme: jekyll-theme-hacker" > ./docs/_config.yml

echo "# Solutions" >> ./docs/index.md

for notebook in $(find . -not -path '*/\.*' -name '*.ipynb'); do

  folder=$(dirname ${notebook/\.\/solutions/docs})

  display=${notebook/\.\/solutions\//}
  display=${display/\.ipynb/}
  
  href=${notebook/\.\/solutions/kaggle-solutions}
  href=${href/\.ipynb/}

  echo " * [$display](https://aguang-xyz.github.io/${href})" >> ./docs/index.md

  mkdir -p $folder

  jupyter nbconvert --to html --output-dir $folder $notebook
done

git add ./docs
git commit -m "Update docs."
