#!/bin/bash

for notebook in $(find . -not -path '*/\.*' -name '*.ipynb'); do

  folder=$(dirname ${notebook/\.\/solutions/docs})

  echo $folder

  mkdir -p $folder

  jupyter nbconvert --to html --output-dir $folder $notebook
done

git add ./docs
git commit -m "Update docs."
